name: Test [Bulut]

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./osmon
    steps:
      - uses: actions/checkout@v3
      - name: Build
      - name: Build
        run: cargo build --verbose
      - name: Run lint
      - name: Run lint
        run: cargo clippy --verbose
      - name: Run tests
      - name: Run tests
        run: cargo test --verbose
