name: Test [Havo]

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./havo
    steps:
      - uses: actions/checkout@v3

      - name: Install required libs
        run: sudo apt install libgccjit-9-dev

      - name: Build
        run: cargo build --release --verbose

#      - name: Run lint
#        run: cargo clippy --verbose

#      - name: Run tests
#        run: cargo test --verbose
